version: '3.8'

services:
  web:
    build: .
    container_name: telegram-recipe-web
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=8000
    volumes:
      - ./recipes.json:/app/recipes.json:ro
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web-network:
    driver: bridge

volumes:
  logs:
