version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-recipe-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./recipes.json:/app/recipes.json:ro
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
